# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ab264ba177a39206d5ccf9caf7c1ffcb14ff37c10b207df34ea0f43411d892062e3c40bd9b30fc7d57de5f1867ab47df6a9a36fdb59c10762f2f7b8739fad6

test:
  secret_key_base: 7f1e4805f66dc1cf7a73b4493b6cfbd1375c15de221d049472c26c59507111fd609c4a4cde0b19fa1fb935b6d38159a77b2aac7cbfb9f9bc77248d18a9f10a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
